name 'mrpapp-idempotent'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mrp application server'
long_description 'Installs/Configures mrp application server'
version '0.3.1'

depends 'apt'
depends 'tomcat', '~> 2.3.1'
depends 'mongodb', '~> 0.16.2'
