name 'mrpapp-idempotent'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mrp application server'
long_description 'Installs/Configures mrp application server'
version '0.2.1'

depends 'apt'
depends 'tomcat', '= 1.0.1'
